### PR TITLE
Minor typo and grammar fixes

### PR DESCRIPTION
**Pull request by DRSDavidSoft**
Dear @stefanrueger, this is some minor typo and grammar fixes that I noticed in the documentation while I was reading it earlier, hope the edits are okay

### CODE REVIEW

**Comment by stefanrueger** [comment]
Thanks. Many good catches! I am, however, partial to 
 - Not using abbreviation dots (eg and ie are both deliberately spelled this way) despite the grammar saying otherwise
 - Using data sheet over datasheet and lower case over lowercase
 - The phrase as it should be, which I consider correct
 
So, happy to merge if above points are reversed to how they were (it's my handwriting :)

**Comment by DRSDavidSoft** [comment]
Sure! Regarding your last point, can you please tell me you mean by the phrase "as it should be"? Since I didn't see or modify this phrase in the text. I'll be sure to apply all changes.

**Comment by stefanrueger** [comment]
> as it should be

Line 311

**Comment by DRSDavidSoft** [comment]
Ah, sorry I didn't notice it. All set now! I think due to the several commits, they should be squished now. Thanks!

**Pull request merged**
